// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zgtdhlozgrnsiyioebzd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpndGRobG96Z3Juc2l5aW9lYnpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyOTE4ODEsImV4cCI6MjA1NTg2Nzg4MX0.VToaAyEqh3-UpS8N65rRE8sBnSb3eqJ8H5UX5A0kVt8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);